name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019] # macos-10.14

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
        
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install eye-native
        run: |
          yarn install --frozen-lockfile
        working-directory: ./eye-native

      - name: Install eye-candy
        run: |
          yarn install --frozen-lockfile
        working-directory: ./eye-candy

      - name: Copy jxi eye-candy
        run: |
          Copy-Item -Path "..\eye-candy-jxi" -Destination "app\node_modules" -Recurse
        working-directory: ./eye-candy

      - name: Build eye-candy
        run: |
          yarn electron-rebuild
        working-directory: ./eye-candy

      - name: Package eye-candy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc
        working-directory: ./eye-candy

      - name: Install eye-projector
        run: |
          yarn install --frozen-lockfile
        working-directory: ./eye-projector

      - name: Copy jxi eye-projector
        run: |
          Copy-Item -Path "..\eye-candy-jxi" -Destination "app\node_modules" -Recurse
        working-directory: ./eye-projector

      - name: Build eye-projector
        run: |
          yarn electron-rebuild
        working-directory: ./eye-projector

      - name: Package eye-projector
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc
        working-directory: ./eye-projector

      - name: Install eye-measure
        run: |
          yarn install --frozen-lockfile
        working-directory: ./eye-measure

      - name: Copy jxi eye-measure
        run: |
          Copy-Item -Path "..\eye-candy-jxi" -Destination "app\node_modules" -Recurse
        working-directory: ./eye-measure

      - name: Build eye-measure
        run: |
          yarn electron-rebuild
        working-directory: ./eye-measure

      - name: Package eye-measure
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc
        working-directory: ./eye-measure
        