name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.14, windows-2019]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14
        working-directory: ./eye-candy

      - name: yarn install
        run: |
          yarn install --frozen-lockfile
        working-directory: ./eye-candy

      - name: yarn electron-rebuild
        run: |
          yarn electron-rebuild
        working-directory: ./eye-candy

      - name: yarn package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc
        working-directory: ./eye-candy
