name: Build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-2019] # macos-10.14

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
        
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install eye-candy
        run: |
          yarn install --frozen-lockfile
        working-directory: ./eye-candy

      - name: Copy jxi eye-candy
        run: |
          ls -la .
          ls -la ./app/
          ls -la ./app/node_modules
          ls -la ../eye-candy-jx
          cp -R ../eye-candy-jxi ./app/node_modules
          ls -la ./app/node_modules
        working-directory: ./eye-candy

      - name: Build eye-candy
        run: |
          yarn electron-rebuild
        working-directory: ./eye-candy

      - name: Package eye-candy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn package-ci
          yarn lint
          yarn tsc
        working-directory: ./eye-candy
